### ISSUE TITLE
Weapons and money Bug 

### ISSUE THREAD

**Issue by 1Lincoin18** [2nd-alarm/FiveM#56]
When you die as a police officer you restart at the Hospital you have no weapon and money  and switching from civilian to police does not restore weapon and ive spent approximately 10,000 ingame salary money on guns Please research and investigate  
                                                Thank you
                 [C42]1Lincoin18 Community support officer

**Comment by Jamie-D-T** [comment]
Please use the correct format and make a new issue

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
